# Generated by Django 5.2.7 on 2026-04-18 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='Alif Mentorship', max_length=200)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Platform Settings',
            },
        ),
        migrations.CreateModel(
            name='AdminNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_new_mentor', models.BooleanField(default=True)),
                ('notify_mentor_verified', models.BooleanField(default=True)),
                ('notify_new_session', models.BooleanField(default=False)),
                ('notify_session_completed', models.BooleanField(default=False)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
