# Generated by Django 5.2.7 on 2025-11-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_studentapplication_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='mentor_profiles/'),
        ),
    ]
