# Generated by Django 5.2.7 on 2026-04-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_platformsettings_adminnotificationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_deactivated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
