# Generated by Django 6.0.1 on 2026-04-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mentor_phone_number_mentor_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='career_goals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='mentorship_interest',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='why_mentorship',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='recommendation_letter',
            field=models.FileField(blank=True, null=True, upload_to='documents/recommendations/'),
        ),
    ]
