# Generated by Django 5.2.7 on 2026-04-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mentorprofile_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='restriction_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
