# Generated by Django 6.0.1 on 2026-04-10 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_mentorship_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('skills_required', models.TextField(blank=True, null=True)),
                ('university_options', models.TextField(blank=True, null=True)),
                ('scholarship_info', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_paths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='StudentGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Exploring', 'Exploring'), ('Decided', 'Decided'), ('Applying', 'Applying'), ('Enrolled', 'Enrolled')], default='Exploring', max_length=20)),
                ('mentor_notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career_path', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_goals', to='api.careerpath')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
