# Generated by Django 6.0.1 on 2026-04-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_savedsearch_mentorfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='timezone',
            field=models.CharField(default='Africa/Mogadishu', max_length=50),
        ),
    ]
