# Generated by Django 5.2.7 on 2026-04-19 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_message_sessionanalytics'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='api_message_sender__06dc5a_idx',
            old_name='api_message_sender_recipient_created_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='api_message_is_read_345e8e_idx',
            old_name='api_message_is_read_recipient_idx',
        ),
    ]
